### PR TITLE
Adjust timings and option to toggle

### PR DESCRIPTION
**Pull request by Torphage**
Adjusted some timings to make sure the tail shows up correctly timed when after a reverse point.

I also added an option that let's you change the visibility of the slider tail. I don't think these types of settings will be handled this way in the future but added it temporarily.

### CODE REVIEW

**Comment by Torphage** [comment]
Should I even pull request on a fork? I'm not too familiar with how I should contribute to others

**Comment by Torphage** [comment]
@mcendu Is it possible to PR this here or should I just make suggestions in your PR at [pp/osu](https://github.com/ppy/osu/pull/7210)?

**Comment by mcendu** [comment]
I am not working on this branch currently.

**Comment by mcendu** [comment]
dead pull request branch

**Pull request closed without merging**
